server:
  port: 8081

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: berkinyardimci98@gmail.com
    password: gvha safh mgqc jahe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true