server:
  port: 7074
spring:
  datasource:
    username: postgres
    password: 1357
    url: jdbc:postgresql://localhost:5432/artBidsAuction
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect